export interface GGMTrackerItem {
  id: string
  name: string
  amount: number
  frequency: 'daily' | 'weekly' | 'monthly' | '10-day' | '8-day' | '14-day'
  type: 'income' | 'outcome'
  category?: string
  recommended?: boolean
  infoTooltip?: string
  supportsQuantity?: boolean
  maxQuantity?: number
  costProgression?: number[] // Array of costs for each quantity level (cumulative or individual based on progressionType)
  progressionType?: 'cumulative' | 'individual' // cumulative = total cost at each level, individual = cost per unit
}

export const ggmTrackerItems: GGMTrackerItem[] = [
  // Income Items - Progression (Estimated)
  {
    id: 'level-reward',
    name: 'Level Reward',
    amount: 140,
    frequency: 'daily',
    type: 'income',
    category: 'Progression (Estimated)',
    infoTooltip: 'Since launch (4th Dec 2024) up to the date 22nd Oct 2025, we had 111 levels with 410 Stellarite each, averaging 140 per day',
  },
  {
    id: 'trial-clear-reward',
    name: 'Trial Clear Reward',
    amount: 32,
    frequency: 'daily',
    type: 'income',
    category: 'Progression (Estimated)',
    infoTooltip: 'Since launch (4th Dec 2024) up to 22nd Oct 2025, we had 11 trials (1 difficulty) + 20 trials (2 difficulties) at 200 Stellarite each, averaging 32 per day',
  },
  {
    id: 'trial-challenge-server-reward',
    name: 'Trial Challenge Server Reward',
    amount: 79,
    frequency: 'daily',
    type: 'income',
    category: 'Progression (Estimated)',
    infoTooltip: 'Since launch (4th Dec 2024) up to 22nd Oct 2025, we had 11 trials (1 difficulty) + 20 trials (2 difficulties) at 500 Stellarite each, averaging 79 per day',
  },
  {
    id: 'echoes-clear-reward',
    name: 'Echoes of War Clear Reward',
    amount: 19,
    frequency: 'daily',
    type: 'income',
    category: 'Progression (Estimated)',
    infoTooltip: 'Since launch (4th Dec 2024) up to 22nd Oct 2025, we had 10 echoes (3 difficulties) at 200 Stellarite each, averaging 19 per day',
  },
  {
    id: 'echoes-challenge-server-reward',
    name: 'Echoes of War Challenge Server Reward',
    amount: 47,
    frequency: 'daily',
    type: 'income',
    category: 'Progression (Estimated)',
    infoTooltip: 'Since launch (4th Dec 2024) up to 22nd Oct 2025, we had 10 echoes (3 difficulties) at 500 Stellarite each, averaging 47 per day',
  },
  // Income Items - Common
  {
    id: 'daily-quest',
    name: 'Daily Journal',
    amount: 60,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'dragon',
    name: 'Dragon Bounty',
    amount: 240,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'weekly-quest',
    name: 'Weekly Journal',
    amount: 200,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'waves-of-horror',
    name: 'Waves of Horror',
    amount: 25,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
    supportsQuantity: true,
    maxQuantity: 18,
    costProgression: [25],
    progressionType: 'individual',
  },
  {
    id: 'guild-quest',
    name: 'Guild Quests',
    amount: 300,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'play-together-sharing',
    name: 'Play Together Sharing',
    amount: 30,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  // Income Items - Travel Events
  {
    id: 'pack-star',
    name: 'Free Stellarite (Pack)',
    amount: 50,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-daily',
    name: 'Monthly Pass - Daily Reward',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-monthly',
    name: 'Monthly Pass - Monthly Bonus',
    amount: 300,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-check-in',
    name: 'Monthly Check-in',
    amount: 240,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  // Income Items - Timed Events
  {
    id: 'slime-event',
    name: 'Slime Event',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'luminous-odyssey',
    name: 'Luminous Odyssey',
    amount: 350,
    frequency: '10-day',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'luminous-odyssey-paid',
    name: 'Luminous Odyssey (Paid Bonus)',
    amount: 400,
    frequency: '10-day',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'tasha-shop',
    name: "Tasha's (Crystal/Forest) - Shop",
    amount: 100,
    frequency: '8-day',
    type: 'income',
    category: 'Timed Events',
    supportsQuantity: true,
    maxQuantity: 10,
    costProgression: [100],
    progressionType: 'individual',
  },
  {
    id: 'special-guest-finding',
    name: 'Special Guest Finding',
    amount: 600,
    frequency: '14-day',
    type: 'income',
    category: 'Timed Events',
  },
  // Outcome Items - Hamster's Goods
  {
    id: 'hamster-black-ash-stone-50',
    name: 'Black Ash Stone (50%)',
    amount: 90,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [90],
    progressionType: 'individual',
  },
  {
    id: 'hamster-super-growth-snacks-50',
    name: 'Super Growth Snacks (50%)',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 6,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-exp-booster',
    name: 'EXP Booster',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [20],
    progressionType: 'individual',
  },
  {
    id: 'hamster-infinity-prism',
    name: 'Infinity Prism Selection',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-branch-of-hearts',
    name: 'Branch of Hearts',
    amount: 60,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [60],
    progressionType: 'individual',
  },
  {
    id: 'hamster-gold-chest-50',
    name: 'Gold Chest (50%)',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-attack-potion',
    name: 'Attack Potion',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 6,
    costProgression: [100],
    progressionType: 'individual',
  },
  {
    id: 'hamster-raw-material',
    name: 'Raw Material',
    amount: 503,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [503],
    progressionType: 'individual',
  },
  {
    id: 'hamster-super-growth-snacks-weekly',
    name: 'Super Growth Snacks',
    amount: 160,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [160],
    progressionType: 'individual',
  },
  {
    id: 'hamster-black-ash-stone-weekly',
    name: 'Black Ash Stone',
    amount: 180,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [180],
    progressionType: 'individual',
  },
  {
    id: 'hamster-gold-chest',
    name: 'Gold Chest',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 10,
    costProgression: [100],
    progressionType: 'individual',
  },
  // Outcome Items - Paper Plane
  {
    id: 'paperplane-pack',
    name: 'PaperPlane Pack',
    amount: 1000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Paper Plane',
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [1000, 2000],
    progressionType: 'individual',
  },
  // Outcome Items - Pack Store
  {
    id: 'star-seeker-pack',
    name: 'Star Seeker Pack',
    amount: 2000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Pack Store',
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [2000, 4000],
    progressionType: 'individual',
  },
  // Outcome Items - Guild Watering
  {
    id: 'guild-watering',
    name: 'Guild Watering',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [20, 70, 170, 370, 570],
    progressionType: 'cumulative',
  },
  // Outcome Items - Quick Purchase
  {
    id: 'quick-artifact-energy',
    name: 'Artifact Energy',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 15,
    costProgression: [30, 80, 160, 280, 430, 580, 730, 950, 1170, 1390, 1610, 1910, 2210, 2510, 2810],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-rune-character',
    name: 'Rune Character',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 15,
    costProgression: [20, 50, 100, 180, 280, 380, 480, 630, 780, 930, 1080, 1280, 1480, 1680, 1880],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-mount-tickets',
    name: 'Mount Tickets',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 9,
    costProgression: [30, 60, 110, 190, 310, 460, 660, 910, 1210],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-cat-fruitwood',
    name: 'Cat Fruitwood',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 9,
    costProgression: [30, 80, 160, 280, 430, 630, 880, 1180, 1480],
    progressionType: 'cumulative',
  },
  // Outcome Items - Rifts
  {
    id: 'rifts-stamina-refill',
    name: 'Stamina Refill',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Rifts',
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [20],
    progressionType: 'individual',
  },
  // Outcome Items - Timed Events
  {
    id: 'tasha-pickaxe',
    name: "Tasha's (Crystal/Forest) - Pickaxe",
    amount: 40,
    frequency: '8-day',
    type: 'outcome',
    category: 'Timed Events',
    supportsQuantity: true,
    maxQuantity: 30,
    costProgression: [40],
    progressionType: 'individual',
  },
]

