export interface GGMTrackerItem {
  id: string
  name: string
  amount: number
  frequency: 'daily' | 'weekly' | 'monthly' | '10-day' | '8-day'
  type: 'income' | 'outcome'
  category?: string
  recommended?: boolean
  supportsQuantity?: boolean
  maxQuantity?: number
  costProgression?: number[] // Array of costs for each quantity level (cumulative or individual based on progressionType)
  progressionType?: 'cumulative' | 'individual' // cumulative = total cost at each level, individual = cost per unit
}

export const ggmTrackerItems: GGMTrackerItem[] = [
  // Income Items - Common
  {
    id: 'daily-quest',
    name: 'Daily Journal',
    amount: 60,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'dragon',
    name: 'Dragon Bounty',
    amount: 240,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'weekly-quest',
    name: 'Weekly Journal',
    amount: 200,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'waves-of-horror',
    name: 'Waves of Horror',
    amount: 200,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'guild-quest',
    name: 'Guild Quests',
    amount: 300,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'play-together-sharing',
    name: 'Play Together Sharing',
    amount: 30,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  // Income Items - Travel Events
  {
    id: 'pack-star',
    name: 'Free Stellarite (Pack)',
    amount: 50,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-daily',
    name: 'Monthly Pass - Daily Reward',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-monthly',
    name: 'Monthly Pass - Monthly Bonus',
    amount: 300,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-check-in',
    name: 'Monthly Check-in',
    amount: 240,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  // Income Items - Timed Events
  {
    id: 'slime-event',
    name: 'Slime Event',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'luminous-odyssey',
    name: 'Luminous Odyssey (10-day)',
    amount: 350,
    frequency: '10-day',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'luminous-odyssey-paid',
    name: 'Luminous Odyssey (Paid Bonus)',
    amount: 400,
    frequency: '10-day',
    type: 'income',
    category: 'Timed Events',
  },
  {
    id: 'tasha-shop',
    name: "Tasha's (Crystal/Forest) - Shop",
    amount: 100,
    frequency: '8-day',
    type: 'income',
    category: 'Timed Events',
    supportsQuantity: true,
    maxQuantity: 10,
    costProgression: [100],
    progressionType: 'individual',
  },
  // Outcome Items - Hamster's Goods
  {
    id: 'hamster-black-ash-stone-50',
    name: 'Black Ash Stone (50%)',
    amount: 90,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [90],
    progressionType: 'individual',
  },
  {
    id: 'hamster-super-growth-snacks-50',
    name: 'Super Growth Snacks (50%)',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    recommended: true,
    supportsQuantity: true,
    maxQuantity: 6,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-exp-booster',
    name: 'EXP Booster',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    recommended: true,
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [20],
    progressionType: 'individual',
  },
  {
    id: 'hamster-infinity-prism',
    name: 'Infinity Prism Selection',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-branch-of-hearts',
    name: 'Branch of Hearts',
    amount: 60,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [60],
    progressionType: 'individual',
  },
  {
    id: 'hamster-gold-chest-50',
    name: 'Gold Chest (50%)',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [50],
    progressionType: 'individual',
  },
  {
    id: 'hamster-attack-potion',
    name: 'Attack Potion',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 6,
    costProgression: [100],
    progressionType: 'individual',
  },
  {
    id: 'hamster-raw-material',
    name: 'Raw Material',
    amount: 503,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [503],
    progressionType: 'individual',
  },
  {
    id: 'hamster-super-growth-snacks-weekly',
    name: 'Super Growth Snacks',
    amount: 160,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [160],
    progressionType: 'individual',
  },
  {
    id: 'hamster-black-ash-stone-weekly',
    name: 'Black Ash Stone',
    amount: 180,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [180],
    progressionType: 'individual',
  },
  {
    id: 'hamster-gold-chest',
    name: 'Gold Chest',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    supportsQuantity: true,
    maxQuantity: 10,
    costProgression: [100],
    progressionType: 'individual',
  },
  // Outcome Items - Paper Plane
  {
    id: 'paperplane-pack',
    name: 'PaperPlane Pack',
    amount: 1000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Paper Plane',
    recommended: true,
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [1000, 2000],
    progressionType: 'individual',
  },
  // Outcome Items - Pack Store
  {
    id: 'star-seeker-pack',
    name: 'Star Seeker Pack',
    amount: 2000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Pack Store',
    supportsQuantity: true,
    maxQuantity: 2,
    costProgression: [2000, 4000],
    progressionType: 'individual',
  },
  // Outcome Items - Guild Watering
  {
    id: 'guild-watering',
    name: 'Guild Watering',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
    recommended: true,
    supportsQuantity: true,
    maxQuantity: 5,
    costProgression: [20, 70, 170, 370, 570],
    progressionType: 'cumulative',
  },
  // Outcome Items - Quick Purchase
  {
    id: 'quick-artifact-energy',
    name: 'Artifact Energy',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 15,
    costProgression: [30, 110, 270, 550, 980, 1560, 2290, 3240, 4410, 5800, 7410, 9320, 11530, 14040, 16850],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-rune-character',
    name: 'Rune Character',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 15,
    costProgression: [20, 70, 170, 350, 630, 1010, 1490, 2120, 2900, 3830, 4910, 6190, 7670, 9350, 11230],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-mount-tickets',
    name: 'Mount Tickets',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 9,
    costProgression: [30, 90, 200, 390, 700, 1160, 1820, 2730, 3940],
    progressionType: 'cumulative',
  },
  {
    id: 'quick-cat-fruitwood',
    name: 'Cat Fruitwood',
    amount: 30,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
    supportsQuantity: true,
    maxQuantity: 9,
    costProgression: [30, 110, 270, 550, 980, 1610, 2490, 3670, 5150],
    progressionType: 'cumulative',
  },
  // Outcome Items - Rifts
  {
    id: 'rifts-stamina-refill',
    name: 'Stamina Refill',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Rifts',
    supportsQuantity: true,
    maxQuantity: 3,
    costProgression: [20],
    progressionType: 'individual',
  },
  // Outcome Items - Timed Events
  {
    id: 'tasha-pickaxe',
    name: "Tasha's (Crystal/Forest) - Pickaxe",
    amount: 40,
    frequency: '8-day',
    type: 'outcome',
    category: 'Timed Events',
    supportsQuantity: true,
    maxQuantity: 30,
    costProgression: [40],
    progressionType: 'individual',
  },
]

