export interface GGMTrackerItem {
  id: string
  name: string
  amount: number
  frequency: 'daily' | 'weekly' | 'monthly'
  type: 'income' | 'outcome'
  category?: string
  recommended?: boolean
}

export const ggmTrackerItems: GGMTrackerItem[] = [
  // Income Items - Common
  {
    id: 'daily-quest',
    name: 'Daily Journal',
    amount: 60,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'dragon',
    name: 'Dragon Bounty',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'weekly-quest',
    name: 'Weekly Journal',
    amount: 200,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'waves-of-horror',
    name: 'Waves of Horror',
    amount: 200,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  {
    id: 'guild-quest',
    name: 'Guild Quests',
    amount: 100,
    frequency: 'weekly',
    type: 'income',
    category: 'Common',
  },
  // Income Items - Travel Events
  {
    id: 'pack-star',
    name: 'Free Stellarite (Pack)',
    amount: 50,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-daily',
    name: 'Monthly Pass - Daily Reward',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-pass-monthly',
    name: 'Monthly Pass - Monthly Bonus',
    amount: 300,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  {
    id: 'monthly-check-in',
    name: 'Monthly Check-in',
    amount: 240,
    frequency: 'monthly',
    type: 'income',
    category: 'Travel Events',
  },
  // Income Items - Timed Events
  {
    id: 'slime-event',
    name: 'Slime Event',
    amount: 100,
    frequency: 'daily',
    type: 'income',
    category: 'Timed Events',
  },
  // Outcome Items - Hamster's Goods (Daily)
  {
    id: 'hamster-super-growth-snacks-50',
    name: 'Super Growth Snacks (50%)',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    recommended: true,
  },
  {
    id: 'hamster-exp-booster',
    name: 'EXP Booster',
    amount: 60,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
    recommended: true,
  },
  {
    id: 'hamster-black-ash-stone-50',
    name: 'Black Ash Stone (50%)',
    amount: 90,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  {
    id: 'hamster-gold-chest-50',
    name: 'Gold Chest (50%)',
    amount: 250,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  // Outcome Items - Hamster's Goods (Additional Daily)
  {
    id: 'hamster-attack-potion',
    name: 'Attack Potion',
    amount: 600,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  {
    id: 'hamster-super-growth-snacks-weekly',
    name: 'Super Growth Snacks',
    amount: 480,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  {
    id: 'hamster-black-ash-stone-weekly',
    name: 'Black Ash Stone',
    amount: 540,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  {
    id: 'hamster-gold-chest-weekly',
    name: 'Gold Chest',
    amount: 1000,
    frequency: 'daily',
    type: 'outcome',
    category: "Hamster's Goods",
  },
  // Outcome Items - Paper Plane
  {
    id: 'paperplane-pack-1k-1',
    name: 'PaperPlane Pack 1k (1st)',
    amount: 1000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Paper Plane',
    recommended: true,
  },
  {
    id: 'paperplane-pack-1k-2',
    name: 'PaperPlane Pack 1k (2nd)',
    amount: 1000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Paper Plane',
    recommended: true,
  },
  // Outcome Items - Pack Store
  {
    id: 'star-seeker-pack-1-1',
    name: 'Star Seeker Pack 1 (1st)',
    amount: 2000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Pack Store',
  },
  {
    id: 'star-seeker-pack-1-2',
    name: 'Star Seeker Pack 1 (2nd)',
    amount: 2000,
    frequency: 'weekly',
    type: 'outcome',
    category: 'Pack Store',
  },
  // Outcome Items - Guild Watering
  {
    id: 'guild-watering-1',
    name: 'Guild Watering (1st Extra)',
    amount: 20,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
    recommended: true,
  },
  {
    id: 'guild-watering-2',
    name: 'Guild Watering (2nd)',
    amount: 50,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
    recommended: true,
  },
  {
    id: 'guild-watering-3',
    name: 'Guild Watering (3rd)',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
  },
  {
    id: 'guild-watering-4',
    name: 'Guild Watering (4th)',
    amount: 200,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
  },
  {
    id: 'guild-watering-5',
    name: 'Guild Watering (5th)',
    amount: 200,
    frequency: 'daily',
    type: 'outcome',
    category: 'Guild Watering',
  },
  // Outcome Items - Quick Purchase
  {
    id: 'quick-150-energy',
    name: '150 Energy',
    amount: 160,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
  },
  {
    id: 'quick-300-rune-character',
    name: '300 Rune Character',
    amount: 100,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
  },
  {
    id: 'quick-15-mount-tickets',
    name: '15 Mount Tickets',
    amount: 110,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
  },
  {
    id: 'quick-150-cat-fruitwood',
    name: '150 Cat Fruitwood',
    amount: 160,
    frequency: 'daily',
    type: 'outcome',
    category: 'Quick Purchase',
  },
]

