export const paperPlaneData = [
  {
    cycle: 0,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: '-',
  },
  {
    cycle: 1,
    type: 'Skill',
    unlockedContent: 'CC1',
    notableReward: 'CC1 Skills',
  },
  {
    cycle: 2,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward:
      'Wind Catching Bag - Double Energy Chance\nEmblem of the King of Kings - Dragon ATK +3%',
  },
  {
    cycle: 3,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 1 Melo Shards',
  },
  {
    cycle: 4,
    type: 'Skill',
    unlockedContent: 'CC2\nCat Bun',
    notableReward: 'CC2 Skills',
  },
  {
    cycle: 5,
    type: 'Artifact',
    unlockedContent: '-',
    notableReward:
      'Ignorant Vision - Double Runes Chance\nDream Realm Artifact - Bonus ATK%',
  },
  {
    cycle: 6,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 1 Melo Shards',
  },
  {
    cycle: 7,
    type: 'Mount',
    unlockedContent: 'Gen 2 Mounts',
    notableReward: 'Gen 2 Mount Tickets / Gen 2 Mount Shards',
  },
  {
    cycle: 8,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'CC2 Skills / Gold Appraisal Medal',
  },
  {
    cycle: 9,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Firefly Path - Double Cat Bun Wood Chance',
  },
  {
    cycle: 10,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 1 Melo Shards',
  },
  {
    cycle: 11,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 2 Mount Shards / Gold Appraisal Medal',
  },
  {
    cycle: 12,
    type: 'Artifact',
    unlockedContent: '-',
    notableReward: 'Corrosive Venom Spear - Double Mount Tickets Chance',
  },
  {
    cycle: 13,
    type: 'Skill',
    unlockedContent: 'CC3',
    notableReward: 'CC3 Skills',
  },
  {
    cycle: 14,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Firefly Path - Double Cat Buns Chance',
  },
  {
    cycle: 15,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 1 Melo Shards',
  },
  {
    cycle: 16,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Cat Bun Selection Box (Pink Cheese) / Gold Appraisal Medal',
  },
  {
    cycle: 17,
    type: 'Mount',
    unlockedContent: 'Gen 3 Mounts',
    notableReward: 'Gen 3 Mount Shards / Gen 3 Mount Tickets',
  },
  {
    cycle: 18,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Corrosive Venom Spear - Double Mount Tickets Chance',
  },
  {
    cycle: 19,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 1 Melo Shards',
  },
  {
    cycle: 20,
    type: 'CatBun',
    unlockedContent: 'Gen 4 Cat Bun',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 21,
    type: 'Artifact',
    unlockedContent: '-',
    notableReward: 'Reduced Recasting Cost Artifact',
  },
  {
    cycle: 22,
    type: 'Skill',
    unlockedContent: 'CC4',
    notableReward: 'CC4 Skills',
  },
  {
    cycle: 23,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Trials Artifact - DMG% and Heal%',
  },
  {
    cycle: 24,
    type: 'Melomon',
    unlockedContent: 'Gen 2 Melo + Wishlist',
    notableReward: 'Gen 1/2 Melo Shards / Gen 2 Melo Strings',
  },
  {
    cycle: 25,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 2 Melo Shards',
  },
  {
    cycle: 26,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 27,
    type: 'Mount',
    unlockedContent: 'Gen 4 Mounts',
    notableReward: 'Gen 4 Mount Tickets',
  },
  {
    cycle: 28,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'EOW Artifact - DMG% + Heal%',
  },
  {
    cycle: 29,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 2 Melo Shards',
  },
  {
    cycle: 30,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 31,
    type: 'Skill',
    unlockedContent: 'CC 5',
    notableReward: 'CC5 Skills',
  },
  {
    cycle: 32,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Core EX Artifact - DMG & Heal',
  },
  {
    cycle: 33,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward:
      'Gen 2 Melo Shards / (KR) Exclusive/General Authority Selector',
  },
  {
    cycle: 34,
    type: 'Mount',
    unlockedContent: '-',
    notableReward:
      'Gen 4 Mount Shards\n(KR) Myth Mount x5\n(KR) Gen 2 Melo Selector',
  },
  {
    cycle: 35,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 36,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Tactical EX Artifact - DMG & Heal',
  },
  {
    cycle: 37,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 2 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 38,
    type: 'Mount',
    unlockedContent: 'Gen 5 Mounts',
    notableReward: 'Gen 5 Mount Tickets',
  },
  {
    cycle: 39,
    type: 'CatBun',
    unlockedContent: 'Gen 5 Catbun',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 40,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Passive EX Artifact - DMG & Heal',
  },
  {
    cycle: 41,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 2 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 42,
    type: 'Skill',
    unlockedContent: 'CC6',
    notableReward: 'CC6 Skills',
  },
  {
    cycle: 43,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward:
      'Gold Appraisal Medal / Random Cat Bun / (KR) Myth Mount x5 / (KR) Gen 2 Melo Selector',
  },
  {
    cycle: 44,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Passive EX Artifact - DMG & Heal',
  },
  {
    cycle: 45,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 2 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 46,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 5 Mount Fragments',
  },
  {
    cycle: 47,
    type: 'Melomon',
    unlockedContent: 'Gen 3 Melo',
    notableReward: 'Gen 2/3 Melo Shards / Gen 3 Melo String',
  },
  {
    cycle: 48,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Artifact (Tactical EX DMG & HEAL)',
  },
  {
    cycle: 49,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 3 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 50,
    type: 'Mount',
    unlockedContent: 'Gen 6 Mounts',
    notableReward: 'Gen 6 Mount Tickets',
  },
  {
    cycle: 51,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Artifact (Core EX DMG & HEAL)',
  },
  {
    cycle: 52,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 6 Mount Fragments',
  },
  {
    cycle: 53,
    type: 'Skill',
    unlockedContent: 'CC7',
    notableReward: 'CC7 Skills',
  },
  {
    cycle: 54,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 3 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 55,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Passive EX Artifact - DMG & Heal',
  },
  {
    cycle: 56,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 6 Mount Fragments',
  },
  {
    cycle: 57,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward:
      'Gold Appraisal Medal / Random Cat Bun / (KR) Flour x25 / (KR) Gen 5 Catbun Selector',
  },
  {
    cycle: 58,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 3 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 59,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Artifact (Tactical EX DMG & HEAL)',
  },
  {
    cycle: 60,
    type: 'Stellar',
    unlockedContent: '-',
    notableReward:
      'Unique Stellar Path Authority\nGeneric Stellar Path Authority',
  },
  {
    cycle: 61,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 3 Melo Shards',
  },
  {
    cycle: 62,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 63,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Artifact (Core EX DMG & HEAL)',
  },
  {
    cycle: 64,
    type: 'Skill',
    unlockedContent: 'CC8',
    notableReward: 'CC8 Skills',
  },
  {
    cycle: 65,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 66,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Double Melo EXP Artifact - 15% Chance',
  },
  {
    cycle: 67,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 3 Melo Shards',
  },
  {
    cycle: 68,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 6 Mount Fragments',
  },
  {
    cycle: 69,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Double Flour Artifact - 10% Chance',
  },
  {
    cycle: 70,
    type: 'Melomon',
    unlockedContent: 'Gen 4 Melo',
    notableReward: 'Gen 3/4 Melo Shards / Gen 4 Melo String',
  },
  {
    cycle: 71,
    type: 'Stellar',
    unlockedContent: '-',
    notableReward:
      'Unique Stellar Path Authority\nGeneric Stellar Path Authority',
  },
  {
    cycle: 72,
    type: 'Mount',
    unlockedContent: 'Gen 7 Mounts',
    notableReward: 'Gen 7 Mount Tickets',
  },
  {
    cycle: 73,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Double Mount Tickets Artifact - 3% Chance',
  },
  {
    cycle: 74,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 4 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 75,
    type: 'Skill',
    unlockedContent: 'CC9',
    notableReward: 'CC9 Skills',
  },
  {
    cycle: 76,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Passive EX Artifact - DMG & Heal',
  },
  {
    cycle: 77,
    type: 'Stellar',
    unlockedContent: '-',
    notableReward:
      'Unique Stellar Path Authority\nGeneric Stellar Path Authority',
  },
  {
    cycle: 78,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 4 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 79,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 7 Mount Tickets',
  },
  {
    cycle: 80,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Tactical EX Artifact - DMG & Heal',
  },
  {
    cycle: 81,
    type: 'Mount',
    unlockedContent: '-',
    notableReward: 'Gen 7 Mount Fragments',
  },
  {
    cycle: 82,
    type: 'Stellar',
    unlockedContent: '-',
    notableReward:
      'Unique Stellar Path Authority\nGeneric Stellar Path Authority',
  },
  {
    cycle: 83,
    type: 'CatBun',
    unlockedContent: '-',
    notableReward: 'Gold Appraisal Medal / Random Cat Bun',
  },
  {
    cycle: 84,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Core EX Artifact - DMG & Heal',
  },
  {
    cycle: 85,
    type: 'Melomon',
    unlockedContent: '-',
    notableReward: 'Gen 4 Melo Shards / Myth Mount Shards',
  },
  {
    cycle: 86,
    type: 'Skill',
    unlockedContent: 'CC10',
    notableReward: 'CC10 Skills',
  },
  {
    cycle: 87,
    type: 'Artifact',
    unlockedContent: 'New Artifact Area',
    notableReward: 'Extra UR Cat Bun Artifact - 5% Chance',
  },
]

export const priorityCycles = [
  2, 5, 9, 12, 14, 18, 21, 23, 24, 25, 28, 33, 37, 41, 45, 47, 49, 54, 58, 61,
  66, 67, 69, 70, 73, 74,
]
